import Head from 'next/head'
import NavBar from "./NavBar";

export default function Layout({ children }) {
 return (
 <>
  <Head>
        <title>tumblr prototype</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <NavBar/>
    {children}
 </>
 )
}